# Values for Apache Airflow Helm chart.
#
# helm repo add apache-airflow https://airflow.apache.org/charts
# helm upgrade --install airflow apache-airflow/airflow -f k8s/airflow/values.yaml --timeout 15m

airflowVersion: "2.11.2"

config:
  core:
    dags_are_paused_at_creation: "True"
  celery:
    operation_timeout: "30.0"

images:
  airflow:
    repository: egisz-airflow-worker
    tag: latest
    pullPolicy: IfNotPresent
  redis:
    repository: redis
    tag: 7.2.5-bookworm
    pullPolicy: IfNotPresent

data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    port: 5432
    db: airflow_db
    sslmode: disable

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    database: airflow_db

extraEnvFrom: |
  - secretRef:
      name: airflow-connections

webserver:
  service:
    type: LoadBalancer
