apiVersion: v1
kind: Secret
metadata:
  name: metabase-connections
type: Opaque
stringData:
  METABASE_ADMIN_EMAIL: "admin@egisz.local"
  METABASE_ADMIN_PASSWORD: "egisz"
  DWH_DB_HOST: "host.docker.internal"
  DWH_DB_PORT: "5432"
  DWH_DB_NAME: "dwh_egisz"
  DWH_BI_USER: "postgres"
  DWH_BI_PASSWORD: "postgres"
